import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CardCreationProvider } from "@/context/test/CardCreationContext";
import { Providers } from "@/providers/Providers";
import RainbowKitContext from "@/context/RainbowkitContext";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-black`}>
        <Providers>
          <RainbowKitContext>
            <CardCreationProvider>
              <main>{children}</main>
            </CardCreationProvider>
          </RainbowKitContext>
        </Providers>
      </body>
    </html>
  );
}
